config/routes.rb
Rails.application.routes.draw do
  get 'about', to: "pages#about", as: :about
  get 'donate', to: "pages#donate", as: :donate
  root 'pages#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
    @title = "About"
    @description = "The World Pro Skiing Foundation Mission"
  end

  def donate
    @title = "Donate"
    @description = "Make a Donation to Support the World Pro Skiing Foundation"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navigation.html.erb
<!-- Header -->
<header id="header">
  <div class="container">
    <div class="row header">
      <!-- Logo -->
      <div class="col-xs-2 logo">
        <%=link_to image_tag("logo.png", alt: "World Pro Skiing"), root_path%>
      </div>
      <!-- //Logo// -->

      <!-- Navigation File -->
      <div class="col-md-10">

        <!-- Mobile Button Menu -->
        <div class="mobile-menu-button">
          <i class="fa fa-list-ul"></i>
        </div>
        <!-- //Mobile Button Menu// -->
        <nav>
          <ul class="navigation">
            <li>
              <%=link_to root_path do %>
                <span class="label-nav">
                  Home
                </span>
                <span class="label-nav-sub" data-hover="The World Pro Skiing Foundation">
                  The World Pro Skiing Foundation
                </span>
              <%end%>
            </li>
            <li>
              <%=link_to about_path do %>
                <span class="label-nav">
                  About
                </span>
                <span class="label-nav-sub" data-hover="Our Mission and Board">
                  Our Mission and Board
                </span>
              <%end%>
            </li>
            <li>
              <%=link_to donate_path do %>
                <span class="label-nav">
                  Donate
                </span>
                <span class="label-nav-sub" data-hover="Support World Pro Skiing">
                  Support World Pro Skiing
                </span>
              <%end%>
            </li>
          </ul>
        </nav>

        <!-- Mobile Nav. Container -->
        <ul class="mobile-nav">
        </ul>
        <!-- //Mobile Nav. Container// -->
      </div>
      <!-- Nav -->

    </div>
  </div>
</header>
<!-- //Header// -->

app/views/layouts/_rev_slider.html.erb
<div class="rev-slider-full">
  <div class="rev-slider-banner-full  rev-slider-full">
    <ul>
      <li data-transition="fade" data-slotamount="7" data-masterspeed="300" >
        <%= image_tag "photos/start.jpg", data: {fullwidthcentering:"on"}%>

        <div class="tp-caption slider-text-title sft str alert alert-grey"
           data-x="20"
           data-y="250"
           data-speed="300"
           data-start="800"
           data-easing="easeOutCubic" data-end="6000" data-endspeed="500">Our Mission</div>


        <div class="tp-caption slider-text-description sft str alert alert-grey"  data-x="20" data-y="315" data-start="1000" data-easing="easeOutBack" data-end="4500" data-endspeed="500">
          The World Pro Skiing Foundation brings business leaders together with world-class athletes<br/>
          to develop these exceptional young people into the leaders of tomorrow.
        </div>
        <div class="tp-caption slider-text-description sft str"  data-x="20" data-y="395" data-start="1500" data-easing="easeOutBack" data-end="5000" data-endspeed="500">
          <%=link_to "More Info", about_path, class:"button btn-flat"%>
        </div>          
      </li>


      <li data-transition="slideleft" data-slotamount="7">
        <%=image_tag "photos/air.jpg"%>

        <div class="tp-caption slider-text-title sfb stl alert alert-grey"
           data-x="right"
           data-y="50"
           data-hoffset="20"
           data-speed="300"
           data-start="800"
           data-easing="easeOutCubic" data-end="6000" data-endspeed="500">Donations</div>


        <div class="tp-caption slider-text-description sfb stl alert alert-grey"  
           data-x="right"
           data-y="115"
           data-hoffset="20" data-start="1000" data-easing="easeOutBack" data-end="4500" data-endspeed="500">
          If our mission resonates, please consider joining us in this worthy journey.<br/>
          Funds will be used to organize and execute these opportunities, from creating<br/>
          workshops and symposia, to supporting internships.  
        </div>
        <div class="tp-caption slider-text-description sfb stl" 
           data-x="right"
           data-y="215"
           data-hoffset="20" data-start="1500" data-easing="easeOutBack" data-end="5000" data-endspeed="500">
          <%=link_to "Donate", donate_path, class:"button btn-flat"%>
        </div>        

      </li>

    </ul>
    <div class="tp-bannertimer tp-bottom"></div>
  </div>
</div>

app/views/layouts/_top_bar.html.erb
<div class="top-bar">
  <div class="container">
    <div class="row">
      <div class="col-sm-7">
      </div>
      <div class="col-sm-5">
        <div class="social-icons">
          <ul>
            <li><%=link_to "Facebook", "https://www.facebook.com/worldproskiing", target: "_blank", class: "social-media-icon facebook-icon", data: {original_title: "facebook"}%></li>
          </ul> 
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_top_title.html.erb
<div class="top-title-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-sm-12">
        <div class="page-info">
          <h1 class="h1-page-title"><%=@title%></h1>

          <h2 class="h2-page-desc">
            <%=@description%>
          </h2>

          <!-- BreadCrumb -->
          <div class="breadcrumb-container">
            <ol class="breadcrumb">
              <li><%=link_to "Home", root_path%></li>
              <li class="active"><%=link_to @title, "#"%></li>
            </ol>
          </div>
          <!-- BreadCrumb -->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
  <title>World Pro Skiing Foundation</title>
  <%= stylesheet_link_tag  'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  
  <!--[if lt IE 9]>
  <script type="text/javascript" src="js/ie-fixes.js"></script>
  <link rel="stylesheet" href="css/ie-fixes.css">
  <![endif]-->

  <meta name="description" content="The world pro skiing foundation is a non-profit organization dedicated to preserving the history of World Pro Skiing and the future of dual-format racing through youth skiing and racing programs">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Fonts -->
  <%= google_webfonts_init({
    google: ['Open Sans', 'Raleway']
  }) %>

  <!--[if lt IE 9]>
  <script type="text/javascript" src="js/respond.js"></script>
  <![endif]-->
  
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
    <div class="top_wrapper">
      <%=render "layouts/top_bar"%>
      <%=render "layouts/navigation"%>

      <%if params[:controller] == "pages" && params[:action] == "home"%>
        <%=render "layouts/rev_slider"%>
      <%end%>        
    </div><!--.top wrapper end -->

    <div class="loading-container">
      <div class="spinner">
        <div class="double-bounce1"></div>
        <div class="double-bounce2"></div>
      </div>
    </div>
    <%=yield%>
    
    <footer>
      <div class="footer">
        <div class="copyright">
          <div class="container">
            <div class="row">
              <div class="col-md-6 col-sm-6 center-text">
                <div class="copyright-text">
                  <%=mail_to "info@worldproskiing.org", "info@worldproskiing.org"%> | (970) 236-6505
                </div>
              </div>
              <div class="col-md-6 col-sm-6 center-text">
                <div class="copyright-text">&copy; <%=Date.today.year%> World Pro Skiing Foundation</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>

  </div><!-- wrapper end -->
</body>
</html>

app/views/pages/donate.html.erb
<div class="content-wrapper hide-until-loading">
  <div class="body-wrapper">
    <div class="section-content no-padding section-color-gray">
      <div class="container">

        <div class="row">
          <div class="col-md-12 col-sm-12">
            <h2 class="h2-section-title">Support the World Pro Skiing Foundation</h2>
            <div class="i-section-title"></div>

            <h3 class="h3-section-info">
              Our mission is clear: find ways to bring business leaders together with world-class athletes to develop these exceptional young people into the leaders of tomorrow. Please consider joining us in this worthy journey. Funds will be used to organize and execute these opportunities, from creating workshops and symposia, to supporting internships. </h3>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12 col-sm-12">
            <form name="PrePage" method = "post" action = "https://Simplecheckout.authorize.net/payment/CatalogPayment.aspx" style="width:180px;" class="centered"> 
              <input type = "hidden" name = "LinkId" value ="f7b7bf9d-7d64-487f-8781-3391d802cf47" /> 
              <input type = "submit" value="Make A Donation" class="button btn-flat" /> 
            </form>
          </div>
          <div class="space-sep20"></div>
        </div>
      </div>
    </div>
    
    <div class="space-sep20"></div>      
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-sm-12 no-bottom-margin">
          <%=image_tag "photos/air_crop.jpg", class:"img-responsive full-width"%>
        </div>
      </div>
    </div>

    <div class="space-sep20"></div>
    <div class="section-content no-padding section-color-gray">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-sm-12 animated" data-animtype="fadeInDown"
             data-animrepeat="0"
             data-speed="1s"
             data-delay="0.2s" visible="true">
            <h2 class="h2-section-title">Our Sponsors</h2>
            <div class="i-section-title"></div>
            <ul class="section-clients">
              <li class="animated" data-animtype="bounceIn" data-animrepeat="0" data-animdelay="0.2s"><%=image_tag "logos/saucony-logo.png", alt:"Saucony", class:"img-responsive client-image" %></li>
              <li class="animated" data-animtype="bounceIn" data-animrepeat="0" data-animdelay="0.3s"><%=image_tag "logos/converse-logo-black.png", alt:"Converse", class:"img-responsive client-image"%></li>
            </ul>
          </div>
        </div>
      </div>

    </div>
    <div class="space-sep20"></div>
  </div>
</div><!--.content-wrapper end -->